title: Herbs Images Classifier
description: Classify herbs images (basil, coriander, mint, parsley) using deep learning
about:


  This is a Herbs Images Classifier using Deep Learning built on top of Pytorch.


  Based on the project built by [Nidhin Pattaniyil](https://npatta01.github.io)
  and [Reshama Shaikh](https://reshamas.github.io).


  More info and the source code can he found below.


  - [Blog](https://reshamas.github.io/deploying-deep-learning-models-on-web-and-mobile/)    

  - [Web app](https://food-img-classifier.herokuapp.com)

  - [Video](https://www.youtube.com/watch?v=7d2qFLeYvRc)


  To try out this mobile app

    - [Expo](https://expo.io/@npatta01/food-app)

    - [Android](https://play.google.com/store/apps/details?id=com.rsnp.foodclassifier)

    - [iOS](https://itunes.apple.com/us/app/food-classifier/id1445356461?ls=1&mt=8)



code: https://github.com/cricket-girl/web-deep-learning-classifier

sampleImages:
  - name: basil
    url: https://upload.wikimedia.org/wikipedia/commons/b/ba/Lasagne_-_stonesoup.jpg
  - name: mint
    url: https://upload.wikimedia.org/wikipedia/commons/6/60/Sushi_platter.jpg
